name = "capslockmode"
version = "0.1.0"
defaultTargets = ["CapslockMode", "capslockmode", "Tests"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.34.0"

[[lean_lib]]
name = "CapslockMode"

[[lean_lib]]
name = "Tests"
globs = ["Tests.+"]

[[lean_exe]]
name = "capslockmode"
root = "Main"
